### PR TITLE
Add rust-version to Cargo.toml

### PR DESCRIPTION
**Pull request by sugyan**
This is to specify that the MSRV (minimum support rust version) of this library is `1.75.0`.

Builds will fail with rustc versions older than 1.74.

```
$ cargo +1.74 build
   Compiling ipld-core v0.3.2 ...
error[E0562]: `impl Trait` only allowed in function and inherent method return types, not in trait method return types
  --> src/codec.rs:42:38
   |
42 |     fn links(bytes: &[u8]) -> Result<impl Iterator<Item = Cid>, Self::LinksError>;
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information

For more information about this error, try `rustc --explain E0562`.
error: could not compile `ipld-core` (lib) due to previous error
```

The return position `impl Trait` pointed out here is from 1.75 to stable.
https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html

I have MSRV 1.70 in my library ATrium, in which case it turns out that I cannot use this library or serde-ipld-dagcbor 0.5, which depends on it.
It would be helpful information for developers like me if that is explicitly stated in the `rust-version`.

### CODE REVIEW

**Comment by vmx** [comment]
Thanks! I wasn't aware that it was that new. Maybe we need to revisit such a function signature, I really want people to be able to use this library.

**Comment by sugyan** [comment]
I am considering raising the MSRV of my library to 1.75 in order to use this `ipld-core`, but it would be great if `ipld-core` itself could be updated to work with 1.74 or lower.

**Comment by vmx** [comment]
@sugyan I'm currently thinking about putting the `Codec` trait behind a feature flag which is enabled by default. So in your case you could not use the default features (I would then bubble it up to `serde_ipld_dagcbor`. Would that work for you (I don't think you need the `Codec` trait)?

This way the MSRV should be way below 1.70.

**Comment by sugyan** [comment]
Hmmm, it looks like I don't need the `Codec` trait in my use case.
If the feature flags exclude Codec from being compiled, `serde_ipld_dagcbor` would also work for my library!

**Comment by vmx** [comment]
I should've done this earlier: I've opened an issue about the high MSRV at https://github.com/ipld/rust-ipld-core/issues/13. Let's discuss further details there.

**Comment by vmx** [comment]
Generally have a `rust-version` field indeed makes sense. But due to the issue discussed at https://github.com/ipld/rust-ipld-core/issues/13 we now have different MSRV, depending on the features being set. AFAIK, this cannot be expressed in the `Cargo.toml`. Hence I'm closing this issue.

But I hope, once we are good with having Rust 1.75 as the MSRV, we can remove the `codec` feature again and use the `rust-version` field.
